auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Fancy
url: http://fannyorz2012.github.io
feed: /atom.xml
author_info: <a href="http://fannyorz2012.github.io/">Fancy</a>
